BEGIN;

-- Ensure symbols table exists (matches your schema layout)
CREATE TABLE IF NOT EXISTS public.symbols (
  symbol      TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  exchange    TEXT,
  asset_type  TEXT,
  ipo_date    DATE,
  delisted    BOOLEAN,
  raw         JSONB,
  created_at  timestamptz DEFAULT now()
);

-- Seed from your LOCAL_NAMES (symbol -> company name)
INSERT INTO public.symbols(symbol, name) VALUES
  ('A','Agilent Technologies'),
  ('AA','Alcoa Corporation'),
  ('AAC','Ares Acquisition'),
  ('AAL','American Airlines Group'),
  ('AAP','Advance Auto Parts'),
  ('AAPL','Apple Inc.'),
  ('ABB','ABB Ltd.'),
  ('ABBV','AbbVie Inc.'),
  ('ABC','AmerisourceBergen'),
  ('ABNB','Airbnb, Inc.'),
  ('ABT','Abbott Laboratories'),
  ('ACN','Accenture plc'),
  ('ADBE','Adobe Inc.'),
  ('ADI','Analog Devices'),
  ('ADM','Archer-Daniels-Midland'),
  ('ADP','Automatic Data Processing'),
  ('ADSK','Autodesk, Inc.'),
  ('AEM','Agnico Eagle Mines'),
  ('AEP','American Electric Power'),
  ('AER','AerCap Holdings'),
  ('AFL','Aflac Incorporated'),
  ('AFRM','Affirm Holdings'),
  ('AGNC','AGNC Investment'),
  ('AIG','American International Group'),
  ('AKAM','Akamai Technologies'),
  ('ALB','Albemarle Corporation'),
  ('ALL','The Allstate Corporation'),
  ('ALLY','Ally Financial'),
  ('ALNY','Alnylam Pharmaceuticals'),
  ('AM','Antero Midstream'),
  ('AMAT','Applied Materials'),
  ('AMC','AMC Entertainment'),
  ('AMD','Advanced Micro Devices'),
  ('AME','AMETEK, Inc.'),
  ('AMGN','Amgen Inc.'),
  ('AMT','American Tower'),
  ('AMZN','Amazon.com, Inc.'),
  ('BA','The Boeing Company'),
  ('BABA','Alibaba Group'),
  ('BAC','Bank of America'),
  ('BBY','Best Buy Co., Inc.'),
  ('BDX','Becton, Dickinson and Company'),
  ('BE','Bloom Energy'),
  ('BEN','Franklin Resources'),
  ('BIIB','Biogen Inc.'),
  ('BK','Bank of New York Mellon'),
  ('BKNG','Booking Holdings'),
  ('BLK','BlackRock, Inc.'),
  ('BMY','Bristol-Myers Squibb'),
  ('C','Citigroup Inc.'),
  ('CAH','Cardinal Health'),
  ('CARR','Carrier Global'),
  ('CAT','Caterpillar Inc.'),
  ('CB','Chubb Limited'),
  ('CBOE','Cboe Global Markets'),
  ('CBRE','CBRE Group'),
  ('CCL','Carnival Corporation'),
  ('CDNS','Cadence Design Systems'),
  ('CDW','CDW Corporation'),
  ('CEG','Constellation Energy'),
  ('CELH','Celsius Holdings'),
  ('CF','CF Industries'),
  ('CHWY','Chewy, Inc.'),
  ('CI','The Cigna Group'),
  ('CL','Colgate-Palmolive'),
  ('CLF','Cleveland-Cliffs'),
  ('CMCSA','Comcast Corporation'),
  ('CME','CME Group'),
  ('CMG','Chipotle Mexican Grill'),
  ('COF','Capital One Financial'),
  ('COIN','Coinbase Global'),
  ('COP','ConocoPhillips'),
  ('COST','Costco Wholesale'),
  ('CRWD','CrowdStrike Holdings'),
  ('CSCO','Cisco Systems'),
  ('CSX','CSX Corporation'),
  ('DAL','Delta Air Lines'),
  ('DE','Deere & Company'),
  ('DELL','Dell Technologies'),
  ('DG','Dollar General'),
  ('DHI','D.R. Horton'),
  ('DHR','Danaher Corporation'),
  ('DIS','The Walt Disney Company'),
  ('DKNG','DraftKings Inc.'),
  ('DLTR','Dollar Tree'),
  ('DOCU','DocuSign'),
  ('DOW','Dow Inc.'),
  ('DPZ','Domino''s Pizza'),
  ('DUK','Duke Energy'),
  ('EA','Electronic Arts'),
  ('EBAY','eBay Inc.'),
  ('ECL','Ecolab Inc.'),
  ('ED','Consolidated Edison'),
  ('EL','Estée Lauder'),
  ('ELV','Elevance Health'),
  ('EMR','Emerson Electric'),
  ('ENPH','Enphase Energy'),
  ('EOG','EOG Resources'),
  ('EQIX','Equinix, Inc.'),
  ('EQT','EQT Corporation'),
  ('ETN','Eaton Corporation'),
  ('ETSY','Etsy, Inc.'),
  ('EW','Edwards Lifesciences'),
  ('EXC','Exelon Corporation'),
  ('F','Ford Motor Company'),
  ('FDX','FedEx Corporation'),
  ('FI','Fiserv, Inc.'),
  ('FSLR','First Solar'),
  ('FTNT','Fortinet, Inc.'),
  ('GE','General Electric'),
  ('GEHC','GE HealthCare'),
  ('GILD','Gilead Sciences'),
  ('GIS','General Mills'),
  ('GM','General Motors'),
  ('GOOG','Alphabet Inc. (Class C)'),
  ('GOOGL','Alphabet Inc. (Class A)'),
  ('GS','Goldman Sachs'),
  ('HD','The Home Depot'),
  ('HON','Honeywell International'),
  ('HPE','Hewlett Packard Enterprise'),
  ('HPQ','HP Inc.'),
  ('HUM','Humana Inc.'),
  ('IBM','International Business Machines'),
  ('ICE','Intercontinental Exchange'),
  ('INTC','Intel Corporation'),
  ('INTU','Intuit Inc.'),
  ('ISRG','Intuitive Surgical'),
  ('JNJ','Johnson & Johnson'),
  ('JPM','JPMorgan Chase & Co.'),
  ('KHC','Kraft Heinz'),
  ('KO','Coca-Cola Company'),
  ('KR','Kroger Co.'),
  ('LIN','Linde plc'),
  ('LLY','Eli Lilly and Company'),
  ('LMT','Lockheed Martin'),
  ('LOW','Lowe''s Companies'),
  ('MA','Mastercard Incorporated'),
  ('MCD','McDonald''s Corporation'),
  ('MCO','Moody''s Corporation'),
  ('MDLZ','Mondelez International'),
  ('MDT','Medtronic plc'),
  ('META','Meta Platforms'),
  ('MMM','3M Company'),
  ('MO','Altria Group'),
  ('MRK','Merck & Co.'),
  ('MRNA','Moderna, Inc.'),
  ('MS','Morgan Stanley'),
  ('MSFT','Microsoft Corporation'),
  ('MU','Micron Technology'),
  ('NFLX','Netflix, Inc.'),
  ('NKE','NIKE, Inc.'),
  ('NOC','Northrop Grumman'),
  ('NOW','ServiceNow'),
  ('NVDA','NVIDIA Corporation'),
  ('OKTA','Okta, Inc.'),
  ('ON','ON Semiconductor'),
  ('ORCL','Oracle Corporation'),
  ('ORLY','O''Reilly Automotive'),
  ('OXY','Occidental Petroleum'),
  ('PANW','Palo Alto Networks'),
  ('PEP','PepsiCo, Inc.'),
  ('PFE','Pfizer Inc.'),
  ('PG','Procter & Gamble'),
  ('PLTR','Palantir Technologies'),
  ('PM','Philip Morris International'),
  ('PNC','PNC Financial Services'),
  ('PSX','Phillips 66'),
  ('PYPL','PayPal Holdings'),
  ('QCOM','Qualcomm Incorporated'),
  ('QRVO','Qorvo, Inc.'),
  ('REGN','Regeneron Pharmaceuticals'),
  ('RIVN','Rivian Automotive'),
  ('ROK','Rockwell Automation'),
  ('ROKU','Roku, Inc.'),
  ('ROP','Roper Technologies'),
  ('RTX','RTX Corporation'),
  ('SBUX','Starbucks Corporation'),
  ('SHOP','Shopify Inc.'),
  ('SMCI','Super Micro Computer'),
  ('SNAP','Snap Inc.'),
  ('SNOW','Snowflake Inc.'),
  ('SO','Southern Company'),
  ('SOFI','SoFi Technologies'),
  ('SPGI','S&P Global'),
  ('SPOT','Spotify Technology'),
  ('SQ','Block, Inc. (Square)'),
  ('STX','Seagate Technology'),
  ('SYK','Stryker Corporation'),
  ('T','AT&T Inc.'),
  ('TEAM','Atlassian'),
  ('TEL','TE Connectivity'),
  ('TGT','Target Corporation'),
  ('TJX','TJX Companies'),
  ('TMO','Thermo Fisher Scientific'),
  ('TMUS','T-Mobile US'),
  ('TSLA','Tesla, Inc.'),
  ('TSM','Taiwan Semiconductor'),
  ('TXN','Texas Instruments'),
  ('UBER','Uber Technologies'),
  ('UNH','UnitedHealth Group'),
  ('UNP','Union Pacific'),
  ('UPS','United Parcel Service'),
  ('V','Visa Inc.'),
  ('VLO','Valero Energy'),
  ('VRSK','Verisk Analytics'),
  ('VRSN','VeriSign, Inc.'),
  ('VRTX','Vertex Pharmaceuticals'),
  ('VZ','Verizon Communications'),
  ('WBD','Warner Bros. Discovery'),
  ('WDAY','Workday, Inc.'),
  ('WFC','Wells Fargo'),
  ('WM','Waste Management'),
  ('WMT','Walmart Inc.'),
  ('XOM','Exxon Mobil'),
  ('YUM','Yum! Brands'),
  ('ZM','Zoom Video Communications'),
  ('ZS','Zscaler, Inc.')
ON CONFLICT (symbol) DO UPDATE SET name = EXCLUDED.name;

COMMIT;
